/*
- One of the first things you discover is that Lightning web components are compiled and minified. Minification makes them smaller and faster for the browser to load. But it also makes them challenging to troubleshoot.
-  Minified code is especially hard to work with because line breaks are removed and variable names are changed. 
- Add breakpoints in DevTools while you're viewing the page in the browser. Breakpoints are easier to set and they don't require code cleanup after using them.
- Breakpoints allow you to pause the JavaScript. While the code is paused, you can view the state of variables and the conditions of your code.
- There are several types of breakpoints
    - Line-of-Code Breakpoints
    - Conditional Line-of-Code Breakpoint
    - Event Listener Breakpoint
*/