// Optimize Customer Data with Standard and Custom Objects

// Object Relationships

- Lookup Relationship
- Master-Detail Relationship

// Schema Builder

- a tool that lets you visualize and edit your data model 

// Importing Data

- Salesforce offers two main methods for importing data: Data Import Wizard, Data Loader
- DIW can import up to 50,000 records at a time into both custom and standard objects
- Data Loader can import up to 150 million records at a time, of any data type, either from files or a database connection. It can be operated either through the UI or the command line. Can be used to schedule regular data loads

// Data Export

- Two main methods for exporting data: 
    - Data Export Service (in-browser service, accessible through the Setup menu, can export data manually once every 7 days or 29 days)
    - Data Loader (client application that can automate export process)