// Using Formula Fields

HYPERLINK() formula can be useful
AND() formula can be used on a checkbox field 

// Roll-Up Summary Fields

Different types of calculations: count number of detail records related to a master record, calculate the sum, minimum, or maximum value


// Create Validation Rules

- Validation rules verify that data entered by users in records meets the standards you specify before they can save it. 
- A validation rule can contain a formula or expression that evaluates the data in one or more fields and returns a value of "true" or "false".addError(- , arg1)